[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
batch_transfer = "CRYsXNCjnhR1dgrpd3rEtY8ec7DNKa2659iCaN5tatXK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts && cargo test-sbf --manifest-path=programs/batch-transfer/Cargo.toml"
