[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
batch_transfer = "De1JkAKuuvfrMhKKai7u53w8Ap8ufvF2QPigQMSMTyEh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_ts = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_rs = "cargo test-sbf --manifest-path=programs/batch-transfer/Cargo.toml"
